# Generated by Django 5.0.3 on 2024-03-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='fatihbahadir', max_length=100),
            preserve_default=False,
        ),
    ]
